<a href="https://colab.research.google.com/github/freezetea/data-science-2026/blob/main/Pertemuan2_%5BAlif_Firdaus_Hidayatullah%5D_%5B250401020166%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama: Alif Firdaus Hidayatullah
NPM: 250401020166

In [26]:
import pandas as pd
import numpy as np

In [28]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"
df = pd.read_csv(url)

In [29]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Q1: Berapa jumlah baris dan kolom dataset Titanic?

In [31]:
print(df.shape, df.columns.tolist())

(891, 12) ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

Q2: Kolom mana yang memiliki nilai kosong
(missing)?

In [32]:
missing = df.isnull().sum()
percent = (missing / len(df)) * 100

pd.DataFrame({
    'Missing': missing,
    'Percent (%)': percent
})

             Missing  Percent (%)
PassengerId        0     0.000000
Survived           0     0.000000
Pclass             0     0.000000
Name               0     0.000000
Sex                0     0.000000
Age              177    19.865320
SibSp              0     0.000000
Parch              0     0.000000
Ticket             0     0.000000
Fare               0     0.000000
Cabin            687    77.104377
Embarked           2     0.224467

Q3: Berapa persen penumpang yang selamat
(Survived=1)?

In [33]:

df['Survived'].mean() * 100

np.float64(38.38383838383838)

Q4: Rata-rata usia penumpang wanita kelas 1 yang
selamat?

In [36]:
wanita_kelas1 = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]
wanita_kelas1.shape[0], wanita_kelas1['Age'].mean()

(94, np.float64(34.61176470588235))

Q5: Kelas penumpang mana yang tingkat
keselamatan tertinggi?

In [38]:
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

Analisa tambahan

In [40]:
df.groupby('Cabin')['Survived'].mean()

Cabin
A10    0.0
A14    0.0
A16    1.0
A19    0.0
A20    1.0
      ...
F33    1.0
F38    0.0
F4     1.0
G6     0.5
T      0.0
Name: Survived, Length: 147, dtype: float64